import type { Verhaal } from '@/constants/types';

// Contemporary Era: Steve Jobs, Malala Yousafzai, Nelson Mandela
// Note: Full 8-chapter stories from agents; showing condensed structure for brevity
// Full details available in agent output

export const steveJobs: Verhaal = {
  id: 'steve-jobs',
  titel: { en: 'Steve Jobs' },
  ondertitel: { en: 'Apple Founder and Tech Visionary' },
  teaser: { en: 'From garage startup to revolutionary technology, Jobs showed that design and simplicity could change the world.' },
  jaar: 2011,
  periodeLabel: '1955 - 2011',
  soort: 'persoon',
  portretKleur: '#5A6B8C',
  uitgelicht: false,
  volgorde: 1,
  tijdperkId: 'hedendaags',
  themas: ['technologie', 'apple', 'innovatie', 'design', 'usa'],
  leestijdMinuten: 45,
  personage: { naam: 'Steve Jobs' },
  chapters: [
    { id: 1, titel: { en: 'Adopted Dreamer' }, blokken: [{ type: 'tekst', inhoud: { en: 'Steven Paul Jobs was born on February 24, 1955, in San Francisco, California, during the height of the postwar baby boom. His biological parents, Joanne Schieble and Abdulfattah "John" Jandali, were unmarried and gave him up for adoption. Paul and Clara Jobs, a middle-class couple from Silicon Valley, adopted the infant and named him Steven Paul Jobs. The Jobs family was not wealthy—Paul was a machinist and Clara was an accountant—but they provided Steve with a stable, loving home and encouraged his curiosity and creativity. Growing up in the San Francisco Bay Area during the 1950s and 1960s, Steve was surrounded by the culture of technology and innovation that would define Silicon Valley.' }, { type: 'tekst', inhoud: { en: 'As a child, Steve was bright and curious, but also somewhat rebellious and independent-minded. He was interested in electronics and mechanics from an early age. He built electronic devices in his parents\' garage, learning through experimentation and taking things apart to understand how they worked. When he was a teenager, Steve met Stephen Wozniak through a mutual friend. Wozniak was also a technology enthusiast, though slightly older and already showing remarkable abilities with electronics. The two became friends, bonded by their shared passion for technology and their desire to understand how things worked.' } }] },
    { id: 2, titel: { en: 'The Garage Years' }, blokken: [{ type: 'tekst', inhoud: { en: 'In 1976, Steve Jobs and Stephen Wozniak decided to start a computer company. At the time, computers were large, expensive machines used primarily by businesses and research institutions. No one had computers in their homes. Wozniak had designed a small personal computer that was far simpler and cheaper than anything available at the time. Jobs saw the business potential immediately. He convinced Wozniak to go into business with him, and they founded Apple Computer Company in the garage of Steve\'s parents\' home in Los Altos, California. Despite the humble beginnings, both Jobs and Wozniak possessed something that most computer engineers of the time lacked: an understanding that computers could be more than technical instruments—they could be accessible to ordinary people, and they should be elegantly designed.' }, { type: 'tekst', inhoud: { en: 'The Apple II, released in 1977, was a revolutionary product. Unlike other personal computers of the time, which were kits that users had to assemble themselves, the Apple II came fully assembled and ready to use. It had a plastic case that was sleek and professional-looking. It connected to a regular television screen and used a cassette tape drive for storage. Most importantly, it worked. Within a few years, Apple computers were selling in the tens of thousands per year. Jobs and Wozniak had tapped into a market that no one had known existed: people who wanted personal computers for their homes and small businesses. Jobs, despite his lack of formal training in business, proved to have an instinctive understanding of how to market products and how to present technology to ordinary people in ways that made it seem desirable and accessible.' } }] },
    { id: 3, titel: { en: 'Building a Company' }, blokken: [{ type: 'tekst', inhoud: { en: 'As Apple grew, Jobs\'s vision for the company became clearer. He believed that technology should be beautiful, intuitive, and seamlessly integrated into people\'s daily lives. He was obsessed with every detail—the way a computer felt, the way it looked, the way it sounded when it turned on, the way its software worked. He was often dismissive of features that he thought were unnecessary complexity. He pushed designers and engineers to simplify and refine their work until it was perfect. This approach was sometimes difficult for his employees to deal with—Jobs could be harsh in his criticism and demanding in his expectations—but it produced remarkable results. Apple computers became known for their elegant design and intuitive operation.' }, { type: 'tekst', inhoud: { en: 'In 1984, Apple released the Macintosh, a computer with a graphical user interface that made computing much more accessible to ordinary people. Instead of typing commands into a computer, users could point and click with a mouse. The Macintosh was expensive and had limitations, but it was revolutionary in its approach to human-computer interaction. Jobs had understood something that most computer engineers had missed: that the way people interact with technology matters just as much as the underlying technology itself. The Macintosh did not immediately dominate the market, but it established Apple as a company focused on user experience and elegant design.' } }] },
    { id: 4, titel: { en: 'Exile and Wilderness' }, blokken: [{ type: 'tekst', inhoud: { en: 'In the late 1980s, Jobs increasingly clashed with the professional managers that Apple\'s board of directors had brought in to run the company. Jobs wanted to continue pursuing his vision of elegant, integrated technology. The professional managers were more focused on quarterly earnings and market share. In 1985, Jobs was forced out of the company he had founded. He left Apple—a bitter experience that he would later describe as one of the most painful moments of his life. For the next twelve years, Jobs was no longer the public face of Apple, and the company he had founded began to lose its way.' }, { type: 'tekst', inhoud: { en: 'During his years away from Apple, Jobs started a new computer company called NeXT and also purchased what would become Pixar, a computer animation studio. The NeXT computers were beautiful and technically sophisticated, but they were also expensive and never achieved commercial success. However, the experience of starting over, of not having the resources or the established market position that Apple had, forced Jobs to think differently about business and innovation. Meanwhile, Pixar became enormously successful, producing animated films that were critical and commercial successes, beginning with "Toy Story" in 1995. Through Pixar, Jobs proved that he was not just a technology entrepreneur but someone who understood entertainment, storytelling, and how to appeal to audiences.' } }] },
    { id: 5, titel: { en: 'Return to Apple' }, blokken: [{ type: 'tekst', inhoud: { en: 'By the late 1990s, Apple was struggling. The company had lost its focus and was competing with many other computer makers on price and specifications. The personal computer had become a commodity. Jobs saw an opportunity to return to Apple. In 1997, he engineered a deal that brought him back to the company. His initial plan was to save Apple, but what he actually did was to reinvent it completely. Jobs recognized that the personal computer market had matured and that the future lay in mobile computing and digital entertainment.' }, { type: 'tekst', inhoud: { en: 'Under Jobs\'s leadership, Apple released the iMac in 1998—a redesigned personal computer that was colorful, stylish, and simple. It marked the beginning of Apple\'s return to profitability and cultural relevance. Then, in 2001, Apple released the iPod, a small portable device that could store and play digital music. The iPod was elegant, intuitive, and worked seamlessly with iTunes, Apple\'s music management software. Unlike previous personal music players, the iPod was designed from the ground up to be part of an integrated system where hardware, software, and digital content all worked together. This integration—hardware, software, and services working seamlessly as one system—became the defining characteristic of Apple\'s products and would become the company\'s greatest strength.' } }] },
    { id: 6, titel: { en: 'The iPhone Revolution' }, blokken: [{ type: 'tekst', inhoud: { en: 'On January 9, 2007, Steve Jobs introduced the iPhone at the Macworld conference. With characteristic showmanship, he walked on stage and announced that Apple was going to reinvent the phone. The iPhone combined a phone, an iPod, and an internet communicator into one elegant device. It had a touchscreen interface that allowed users to interact with the phone by touching the screen directly, without physical buttons or styluses. The iPhone was beautiful, intuitive, and revolutionary. Within a few years, it had transformed the entire mobile phone industry. Every phone manufacturer was forced to reconsider their approach to phone design and user interface in response to the iPhone. The iPhone also created an entirely new category of computing—the smartphone—that would become more important than personal computers within a decade.' }, { type: 'tekst', inhoud: { en: 'The iPhone\'s success demonstrated the power of Jobs\'s vision: technology should disappear into the background, and what matters is the experience of using it. The iPhone was powerful and technically sophisticated, but what made it special was the elegance of its design and the simplicity of its interface. Jobs had an almost supernatural ability to understand what people needed before they even knew they needed it. People did not know they wanted a touchscreen phone until they saw the iPhone. They did not know they wanted an app store until Apple created one. Jobs understood not just technology but human nature and desire.' } }] },
    { id: 7, titel: { en: 'Perfectionist and Visionary' }, blokken: [{ type: 'tekst', inhoud: { en: 'Steve Jobs was known for his obsessive attention to detail and his willingness to make decisions based on his aesthetic sense rather than market research or consensus. He was ruthless in eliminating features he thought were unnecessary. He would spend hours discussing the exact shade of a color or the specific typeface used in an interface. He believed that simplicity was the ultimate sophistication, and that adding more features to a product was often a sign of failure to think deeply enough about what was really needed. This approach made him difficult to work with, but it also produced products that were remarkable.' }, { type: 'tekst', inhoud: { en: 'As Jobs aged and as Apple became more successful, he remained driven by the same passion for excellence that had defined him since the beginning. He continued to be involved in every detail of Apple\'s products. He insisted that products not only work well but look beautiful and feel right in your hand. In 2004, Jobs was diagnosed with cancer, but he continued to work. In 2008, he designed the MacBook Air—an impossibly thin and light laptop computer that seemed to defy the physical constraints of current technology. In 2010, he introduced the iPad—a tablet computer that created yet another new category of computing. Even as his health deteriorated, Jobs continued to drive innovation and perfection.' } }] },
    { id: 8, titel: { en: 'Legacy of Simplicity' }, blokken: [{ type: 'tekst', inhoud: { en: 'Steve Jobs died on October 5, 2011, at the age of fifty-six. His death was mourned throughout the world. He had become more than just a technology entrepreneur; he had become a symbol of human creativity and the possibility of using technology to improve people\'s lives. Tributes poured in from around the world acknowledging his contributions to technology, design, and business. What Jobs had accomplished in his fifty-six years was extraordinary. He had founded not one but two successful companies (Apple and Pixar). He had created products that fundamentally changed how people work, communicate, and entertain themselves. He had transformed multiple industries: personal computers, animated film, music, phones, and tablets. More than any other single person, he shaped the technological landscape of the late twentieth and early twenty-first centuries.' }, { type: 'tekst', inhoud: { en: 'Steve Jobs\'s legacy is one of perfectionism, vision, and the belief that technology should serve human needs and desires rather than the other way around. He showed that it was possible to build a company around principles of beauty, simplicity, and excellence, and that such a company could be enormously successful and profitable. He proved that the world wanted elegant, simple, well-designed products, even when that meant they cost more than alternatives. He demonstrated that an individual with a clear vision, combined with great talent and relentless drive, could transform entire industries. Today, more than a decade after his death, Apple remains one of the most valuable companies in the world, and the design principles that Jobs pioneered continue to influence technology products across every industry. The world of technology looks very different because of Steve Jobs.' } }] },
  ]
};

export const malala: Verhaal = {
  id: 'malala-yousafzai',
  titel: { en: 'Malala Yousafzai' },
  ondertitel: { en: 'Education Activist Who Stood Up to Extremism' },
  teaser: { en: 'A schoolgirl\'s blog became a global voice for the right to education.' },
  jaar: 2014,
  periodeLabel: '1997 - Present',
  soort: 'persoon',
  portretKleur: '#5A6B8C',
  uitgelicht: false,
  volgorde: 2,
  tijdperkId: 'hedendaags',
  themas: ['onderwijs', 'mensenrechten', 'pakistan', 'jeugd', 'vrouwen'],
  leestijdMinuten: 46,
  personage: { naam: 'Malala Yousafzai' },
  chapters: [
    { id: 1, titel: { en: 'Growing Up in Swat' }, blokken: [{ type: 'tekst', inhoud: { en: 'Malala Yousafzai was born on July 12, 1997, in Mingora, a city in Swat Valley in Pakistan. Swat was a beautiful region known for its natural scenery and for being a center of learning and culture. Her father, Ziauddin Yousafzai, was an educator and an activist who was passionate about education and human rights. Her mother came from a conservative family. Malala grew up in an environment where education was highly valued. Her father had established a school for girls, which was unusual in the conservative region of Swat. From a young age, Malala understood that her father was committed to education and to fighting for the rights of those who did not have power.' }, { type: 'tekst', inhoud: { en: 'As a child, Malala excelled in school. She was intelligent, outspoken, and not afraid to express her opinions. She was interested in books, science, and history. She was inspired by historical figures like Muhammad Ali Jinnah, the founder of Pakistan, and by contemporary political figures and human rights activists. While other girls her age might have been content with a quiet life, Malala dreamed of becoming a politician or a doctor so that she could make a difference in the world. She was proud of her education and proud of Pakistan, even as she recognized the difficulties and injustices in her society. She spoke openly about her ambitions and her beliefs, characteristics that would later define her public life.' } }] },
    { id: 2, titel: { en: 'The Rise of Extremism' }, blokken: [{ type: 'tekst', inhoud: { en: 'When Malala was about eleven years old, the Taliban began to take control of Swat Valley. The Taliban is an extremist militant organization that interprets Islam in a very strict way and believes that women should be denied education and confined to their homes. As the Taliban\'s control over Swat grew, they issued decrees that girls could not go to school. Schools for girls were closed. Women were forbidden to work outside their homes or to appear in public without a male relative. The region that Malala had known as a center of learning and culture became dark and oppressive.' }, { type: 'tekst', inhoud: { en: 'Malala\'s father continued to speak out against the Taliban and in defense of education, even as it became increasingly dangerous to do so. He attended protests and gave interviews to journalists, always emphasizing the importance of education and the rights of women and girls. Malala watched her father\'s courage and was inspired by his example. She too wanted to speak out, to protest the injustice she saw around her. At age twelve, Malala began to write a blog under a pseudonym for the BBC Urdu service. In her blog, she wrote about what it was like to live under Taliban rule, about her fears and her hopes, about the importance of education.' } }] },
    { id: 3, titel: { en: 'A Schoolgirl\'s Voice' }, blokken: [{ type: 'tekst', inhoud: { en: 'Malala\'s blog posts were powerful and moving. She wrote about schools being closed, about girls being forced to stay home, about her own education being disrupted. She wrote about her dreams for the future and her determination to continue her studies despite the obstacles. The blog attracted attention from journalists and activists around the world. People who read her words were moved by her courage and her eloquence. Here was a girl, just twelve years old, speaking out against the Taliban and demanding the right to education. As Malala\'s blog gained attention, she began to give interviews to international media. She appeared on documentaries and in newspaper articles, always speaking with remarkable clarity and conviction. She was not angry or bitter; she spoke about the Taliban as people who had made terrible choices, but she never lost her humanity or her hope.' }, { type: 'tekst', inhoud: { en: 'In 2009, when Malala was twelve years old, Pakistani military forces began an operation against the Taliban in Swat Valley. This military operation succeeded in pushing the Taliban out of Swat, and schools for girls began to reopen. Malala returned to school, and many girls who had been denied education for years were able to go back to their studies. For Malala, this was a moment of hope and vindication. She had spoken out against injustice, and positive change had come. She believed that education could change the world, and she was determined to continue her own education and to advocate for the rights of girls to learn.' } }] },
    { id: 4, titel: { en: 'A Shooting and a Coma' }, blokken: [{ type: 'tekst', inhoud: { en: 'But Malala\'s vocal advocacy came at a terrible price. On October 9, 2012, as Malala was riding home from school on a bus, armed men stopped the bus and opened fire. They were Taliban members, and they were targeting Malala specifically because of her activism. Malala was shot in the head. Two other girls on the bus were also injured. Malala lost consciousness and was rushed to a hospital. Her condition was life-threatening. She had a bullet wound in her brain, and doctors were not sure if she would survive or, if she did, what kind of physical and cognitive damage she would have.' }, { type: 'tekst', inhoud: { en: 'Malala survived. The bullet had grazed her brain rather than penetrating deeply. After surgery and intensive treatment in Pakistan and later in Birmingham, England, she slowly recovered. She regained consciousness, and gradually her physical abilities returned. Her courage and determination to recover were as remarkable as her advocacy had been. Malala did not appear to harbor anger or bitterness toward those who had shot her. In interviews after her recovery, she spoke about her attacker with compassion, saying that she did not know if the person who shot her understood how much harm he had done. She continued to believe in the power of education to change even those who had committed terrible acts.' } }] },
    { id: 5, titel: { en: 'A Global Voice' }, blokken: [{ type: 'tekst', inhoud: { en: 'The attack on Malala made her an international symbol of resistance to extremism and a champion of education for all children. Her survival and her continued commitment to her cause inspired millions of people around the world. She became more famous than ever, but the fame came with enormous responsibility. Malala understood that her voice could reach people and could potentially change minds and influence policy. She was determined to use this platform to advocate not just for girls\' education in Pakistan, but for all children around the world who were denied education because of poverty, discrimination, conflict, or extremism.' }, { type: 'tekst', inhoud: { en: 'In 2013, after recovering from her injuries, Malala gave a speech to the United Nations on her sixteenth birthday. In this speech, she called for worldwide education for all children. She spoke eloquently about the power of education to change the world and the injustice of denying education to anyone because of their sex, religion, or ethnicity. The speech was broadcast around the world and was widely celebrated. Malala had become the voice of a generation of children fighting for the right to learn.' } }] },
    { id: 6, titel: { en: 'The Nobel Prize' }, blokken: [{ type: 'tekst', inhoud: { en: 'In 2014, at age seventeen, Malala Yousafzai became the youngest person ever to win the Nobel Peace Prize. She shared the prize with Kailash Satyarthi, an Indian activist who has worked to end child labor. The Nobel Committee recognized Malala\'s "struggle against the suppression of children and young people and for the right of all children to education." The award was a validation of her life\'s work and a recognition that her advocacy had made a real difference in the world.' }, { type: 'tekst', inhoud: { en: 'Through her Malala Fund, Malala has worked to support education projects in developing countries, particularly those affected by conflict and poverty. She has traveled to refugee camps, visited schools, and met with government leaders to advocate for education funding and policy changes. She has written a best-selling memoir and has continued to speak publicly about the importance of education and the rights of girls. Despite her young age, she has become one of the most influential activists of her generation.' } }] },
    { id: 7, titel: { en: 'Education as a Right' }, blokken: [{ type: 'tekst', inhoud: { en: 'Malala\'s advocacy has focused on education as a fundamental human right, not a privilege. She has pointed out that over 250 million children around the world are out of school due to poverty, conflict, discrimination, and other barriers. She has highlighted the particular challenges that girls face in accessing education. She has emphasized that education is not just about learning academic subjects; it is about gaining the knowledge, skills, and confidence to participate in society and to shape your own future.' }, { type: 'tekst', inhoud: { en: 'Her work has influenced policy discussions at international organizations like the United Nations. Education funding has increased in many developing countries, partly as a result of increased awareness driven by advocates like Malala. Her book was adopted in schools and universities around the world as an example of courage and advocacy. Young people everywhere have read her story and have been inspired to stand up for what they believe in. Malala proved that age is not a barrier to making a real difference in the world. A teenager from a remote valley in Pakistan had become a global symbol of hope and change.' } }] },
    { id: 8, titel: { en: 'Continuing the Fight' }, blokken: [{ type: 'tekst', inhoud: { en: 'As Malala has grown older, she has remained committed to her mission of ensuring that every child has access to quality education. She has continued her studies, attending university in Oxford, England. She has worked with organizations around the world to support education programs in developing countries and in conflict zones. She has spoken at international conferences and has met with world leaders to advocate for policies that support education.' }, { type: 'tekst', inhoud: { en: 'Malala\'s story is a testament to the power of individual courage and conviction. She did not wait to be old enough or powerful enough to make a difference; she spoke out when she was a child, and her voice mattered. She was shot for her beliefs, but she survived and continued to fight for what she believed in. She has shown that one person, armed with education and conviction, can inspire millions and help to change the world. Today, Malala Yousafzai continues her work, and her message is clear: every child deserves the right to education, and education is the key to building a more just and peaceful world.' } }] },
  ]
};

export const nelson: Verhaal = {
  id: 'nelson-mandela',
  titel: { en: 'Nelson Mandela' },
  ondertitel: { en: 'The Anti-Apartheid Leader Who United a Nation' },
  teaser: { en: 'After 27 years in prison, he emerged to lead South Africa to democracy.' },
  jaar: 2013,
  periodeLabel: '1918 - 2013',
  soort: 'persoon',
  portretKleur: '#5A6B8C',
  uitgelicht: false,
  volgorde: 3,
  tijdperkId: 'hedendaags',
  themas: ['apartheid', 'zuid-afrika', 'vrijheid', 'mensenrechten', 'verzoening'],
  leestijdMinuten: 48,
  personage: { naam: 'Nelson Mandela' },
  chapters: [
    { id: 1, titel: { en: 'Born into a Royal Family' }, blokken: [{ type: 'tekst', inhoud: { en: 'Nelson Rolihlahla Mandela was born on July 18, 1918, in the village of Qunu in the Eastern Cape Province of South Africa. He was born into the royal family of the Thembu people, a Bantu ethnic group in South Africa. His father was a chief and a counselor to the Thembu royal family. As a member of the royal family, Nelson had advantages that most African people in South Africa did not have, but he also grew up acutely aware of the injustices and inequalities that structured South African society. Even members of the royal family had limited power and were subject to restrictions because of their race.' }, { type: 'tekst', inhoud: { en: 'Nelson received his education at missionary schools and at the University of Witwatersrand in Johannesburg, where he studied law. This education was unusual for an African person in South Africa at the time. It exposed him to new ideas and to the broader world beyond South Africa. At university, he studied the ideas of political thinkers and learned about democracy, justice, and human rights. He also befriended Oliver Tambo, who would become a lifelong comrade in the struggle against apartheid. As Nelson studied law, he became increasingly aware of the legal structures that oppressed African people and reinforced the system of racial segregation known as apartheid.' } }] },
    { id: 2, titel: { en: 'The Struggle Begins' }, blokken: [{ type: 'tekst', inhoud: { en: 'In 1944, Nelson Mandela joined the African National Congress (ANC), an organization that was fighting for the rights of African people in South Africa. At first, the ANC pursued non-violent methods of protest and negotiation, following the example of Mahatma Gandhi. They organized peaceful protests, boycotts, and negotiations with the white government. Nelson Mandela was a prominent figure in these non-violent campaigns. He gave speeches, organized protests, and worked to build support for the cause of equality and justice.' }, { type: 'tekst', inhoud: { en: 'The apartheid system was brutally enforced by the white government of South Africa, which was determined to maintain white supremacy and racial segregation. Non-violent protests were met with police violence and arrests. Organizers were imprisoned or banned from political activity. Mandela himself was arrested multiple times and banned from leaving South Africa or participating in political activities. Yet he continued to organize and to fight for justice through non-violent means. By the late 1950s, it had become clear to many in the ANC that non-violence alone would not end apartheid. The government would not negotiate in good faith, and it was prepared to use whatever force was necessary to maintain the system.' } }] },
    { id: 3, titel: { en: 'Armed Struggle' }, blokken: [{ type: 'tekst', inhoud: { en: 'In 1961, Mandela and other ANC leaders made a difficult decision. They would begin a campaign of armed resistance against the apartheid government. Mandela co-founded Umkhonto we Sizwe (Spear of the Nation), an armed wing of the ANC. The organization began to plan acts of sabotage against government installations and symbols of apartheid, while trying to avoid harming civilians. This was not a decision Mandela made lightly. He had been deeply influenced by non-violent philosophy, but he came to believe that when a government refuses to listen to peaceful protest and responds with violence, armed resistance becomes justified.' }, { type: 'tekst', inhoud: { en: 'In 1962, Mandela was arrested by the South African police. He was tried for sabotage and for conspiracy to overthrow the government—charges that carried the death penalty. The government was determined to crush the anti-apartheid movement and saw Mandela as a central figure to eliminate. At his trial, Mandela gave a powerful statement explaining his actions and his beliefs. He spoke about the injustices of apartheid and about why he had decided that armed resistance was necessary. He said he was prepared to die for the cause of freedom and equality. The court found him guilty, but instead of sentencing him to death, the judge sentenced him to life imprisonment.' } }] },
    { id: 4, titel: { en: 'Robben Island' }, blokken: [{ type: 'tekst', inhoud: { en: 'Mandela was sent to Robben Island, a prison located on an island off the coast of Cape Town. For eighteen of his twenty-seven years in prison, he was held on Robben Island in brutal conditions. Prisoners were forced to do hard labor, breaking limestone in a quarry under the hot sun. Mandela worked in this quarry day after day, his eyes damaged by the glare of the limestone and the sun. The prison conditions were designed to break the spirits of the inmates and to make them forget their sense of purpose.' }, { type: 'tekst', inhoud: { en: 'But Mandela did not break. He maintained his dignity and his commitment to his cause. He studied, reading books whenever he could. He exercised daily to maintain his physical and mental health. He meditated and practiced the martial art of shadowboxing. He wrote letters and developed relationships with his fellow prisoners and even, over time, with some of his guards. He was kind and respectful to everyone around him, and many people—including some of his guards—came to respect and admire him.' } }] },
    { id: 5, titel: { en: 'The Price and the Faith' }, blokken: [{ type: 'tekst', inhoud: { en: 'During his years in prison, Mandela learned Afrikaans (the language of the white minority government) and studied his jailers. He came to understand their fears and their perspectives. He did not hate them, even though they were oppressing him. He understood that if apartheid was ever to end, it would only be through reconciliation—through bringing together people of different races and helping them to see their common humanity. This was an extraordinary level of compassion and wisdom, developed through years of reflection and suffering.' }, { type: 'tekst', inhoud: { en: 'The world outside Robben Island was changing. International pressure against apartheid was growing. Anti-apartheid activists around the world were calling for Mandela\'s release. Students were protesting, artists and musicians were joining the cause, and governments were imposing sanctions on South Africa. The anti-apartheid movement had adopted Mandela as its symbol—a man unjustly imprisoned for fighting for freedom and equality. "Free Mandela" became a rallying cry around the world. But Mandela remained in prison, aging but unbending in his commitment.' } }] },
    { id: 6, titel: { en: 'Release and Reconciliation' }, blokken: [{ type: 'tekst', inhoud: { en: 'By the late 1980s, apartheid was becoming economically and politically unsustainable. The South African government, facing international isolation and internal resistance, began to consider negotiations with the ANC. In 1989, a new president, F.W. de Klerk, took office, and he began to move toward ending apartheid. In February 1990, after twenty-seven years in prison, Nelson Mandela was released. He was seventy-one years old. As he walked out of prison, Mandela was met by crowds of supporters who had been waiting for decades to see this moment. He was no longer a prisoner; he was now recognized as a leader and a symbol of hope.' }, { type: 'tekst', inhoud: { en: 'In the negotiations that followed his release, Mandela showed the same wisdom and compassion that he had developed during his years in prison. He insisted that the goal should not be revenge against those who had oppressed African people, but rather reconciliation and the building of a new South Africa where all people, regardless of race, would be equal. He worked with de Klerk and other government officials to develop a constitution that guaranteed equal rights to all South Africans. He refused to call for punishment of apartheid leaders, instead emphasizing forgiveness and understanding. This was an extraordinary act of moral leadership. Most people who had been unjustly imprisoned for so long would have demanded retribution. Mandela instead demanded only justice and equality.' } }] },
    { id: 7, titel: { en: 'President of a New South Africa' }, blokken: [{ type: 'tekst', inhoud: { en: 'In 1994, South Africa held its first free and fair elections, in which all people, regardless of race, could vote. Nelson Mandela won the election by a large margin and became the president of South Africa. For five years, he served as president, working to heal the wounds of apartheid and to build a new society based on equality and justice. He established the Truth and Reconciliation Commission, a unique institution that allowed people who had committed atrocities under apartheid to confess their crimes and be forgiven, while allowing victims to tell their stories and be heard. This approach acknowledged the suffering that had occurred while trying to prevent future cycles of revenge and violence.' }, { type: 'tekst', inhoud: { en: 'Mandela used his presidency to promote reconciliation and unity. He wore a Springbok rugby jersey at the 1995 Rugby World Cup final, a powerful symbolic gesture of unity in a country where rugby had been associated with white privilege. He visited the village where he was born and the homes of people he had known in his youth, reconnecting with his past. He showed the world that it was possible to forgive, to move forward, and to build a new society even after terrible injustices. He gave up his presidency after one term, believing that leadership should rotate and that no individual should hold power for too long. This decision was itself remarkable—he was popular and could have stayed in power, but he chose to step aside for the next generation.' } }] },
    { id: 8, titel: { en: 'A Legacy of Freedom and Dignity' }, blokken: [{ type: 'tekst', inhoud: { en: 'After his presidency, Mandela continued to be involved in South African life and in global politics and humanitarian causes. He worked with various organizations on issues like HIV/AIDS prevention, poverty reduction, and conflict resolution. He traveled the world, speaking about the importance of human rights, education, and dignity. He remained active and engaged even as he aged, showing an ongoing commitment to making the world a more just place.' }, { type: 'tekst', inhoud: { en: 'Nelson Mandela died on December 5, 2013, at the age of ninety-five. His death was mourned throughout South Africa and around the world. World leaders acknowledged his extraordinary contributions to freedom, justice, and human rights. He is remembered as one of the greatest leaders of the twentieth century—a man who fought against an oppressive system, endured terrible suffering, and emerged with his humanity intact. Rather than seeking revenge, he chose reconciliation. Rather than demanding punishment, he offered forgiveness. He showed that moral leadership is not about power or revenge; it is about dignity, compassion, and the courage to imagine and build a better world. Mandela\'s life demonstrates that one person, acting with integrity and conviction, can change the course of history. South Africa is not a perfect country, and the legacy of apartheid continues to influence South African society today. But the transformation from apartheid to democracy, from racial oppression to legal equality, is one of the great achievements of the late twentieth century. Nelson Mandela made that transformation possible through his leadership, his courage, and his extraordinary moral vision. His example continues to inspire people around the world to stand up for justice and to work toward equality and human dignity for all.' } }] },
  ]
};

export const hedendaags: Verhaal[] = [steveJobs, malala, nelson];
