import type { Verhaal } from '@/constants/types';

// Content generated from 20th Century agent (3 stories with 8 chapters each)
// Full details: Marie Curie, Winston Churchill, Martin Luther King Jr.

export const marieCurie: Verhaal = {
  id: 'marie-curie',
  titel: { en: 'Marie Curie' },
  ondertitel: { en: 'The Scientist Who Unveiled the Power of Atoms' },
  teaser: { en: 'Born in Warsaw, she discovered the hidden forces within matter itself—and changed science forever.' },
  jaar: 1934,
  periodeLabel: '1867 - 1934',
  soort: 'persoon',
  portretKleur: '#6B8E4F',
  uitgelicht: false,
  volgorde: 1,
  tijdperkId: 'twintigste-eeuw',
  themas: ['wetenschap', 'radioactiviteit', 'vrouwen', 'Frankrijk', 'atoom'],
  leestijdMinuten: 45,
  personage: { naam: 'Marie Curie' },
  chapters: [
    { id: 1, titel: { en: 'A Polish Girl Dreams of Science' }, blokken: [{ type: 'tekst', inhoud: { en: 'Maria Skłodowska was born in Warsaw, Poland, in 1867, during a time when few girls were permitted to pursue science. Her childhood was marked by tragedy. When she was only eight years old, her eldest sister died of typhus. Two years later, her mother succumbed to tuberculosis. These losses shaped Maria\'s character, giving her a fierce determination to achieve something meaningful with her life. Despite her grief, she was captivated by the world of science—by chemistry, physics, and the mysteries of nature that seemed to hold infinite answers.' }, { type: 'tekst', inhoud: { en: 'In Russian-occupied Warsaw, where her family lived, attending university was forbidden for women. But Maria was undeterred. She attended secret "floating schools"—underground educational gatherings held in different locations to avoid Russian authorities. There, she studied with other eager young people, absorbing every bit of knowledge she could gather. Her teachers recognized her exceptional talent. By her late teens, Maria had made a decision: she would leave Poland and travel to Paris, where women were allowed to study at universities. It was a bold move for a young woman traveling alone in the 1890s, but Maria was ready to seize this opportunity.' } }] },
    { id: 2, titel: { en: 'From Warsaw to Paris' }, blokken: [{ type: 'tekst', inhoud: { en: 'In 1891, at the age of 23, Maria arrived in Paris with almost no money in her pockets. She enrolled at the University of Paris, one of the first female physics students in the institution\'s history. Life was difficult. She lived in a small, freezing room in the Latin Quarter, surviving on bread, chocolate, and eggs. Sometimes she had so little food that she would faint during her studies. Despite these hardships, Maria threw herself into her work with remarkable intensity. She attended lectures, performed experiments, and read everything she could find about the latest discoveries in physics and chemistry.' }, { type: 'tekst', inhoud: { en: 'In 1893, she earned her degree in physics—ranking first in her examinations. A year later, she obtained another degree in mathematics, ranking second. By this time, Maria had adopted the French version of her name: Marie. Her dedication and brilliance had not gone unnoticed. Through a Polish physicist friend, Marie was introduced to Pierre Curie, a talented scientist who had made important discoveries in crystallography. When they met in 1894, it was clear that they shared not only a passion for science but also a connection that would change both their lives. They married in July 1895, beginning a partnership that would lead to some of the greatest scientific discoveries of the age.' } }] },
    { id: 3, titel: { en: 'The Mystery of Rays' }, blokken: [{ type: 'tekst', inhoud: { en: 'In 1896, Marie chose an exciting topic for her doctoral research. Just one year earlier, Wilhelm Röntgen had discovered X-rays, and Henri Becquerel had noticed that uranium emitted mysterious rays. The scientific world was ablaze with curiosity. Marie decided to investigate these rays more thoroughly using an electrometer—a sensitive instrument that Pierre and his brother had invented. This device could measure tiny electrical currents with remarkable precision, making it perfect for studying these invisible radiations.' }, { type: 'tekst', inhoud: { en: 'Working in a converted shed that served as a laboratory, Marie tested numerous elements and minerals. She discovered that the strength of the rays was proportional to the amount of uranium present—not to the chemical compounds it formed. This meant the rays came from the atom itself, a revolutionary idea. But then she noticed something puzzling. Some minerals emitted far more rays than their uranium content would predict. Marie hypothesized that these minerals must contain unknown elements that were even more radioactive than uranium. This intuition would prove correct.' }, { type: 'tekst', inhoud: { en: 'Working alongside Pierre, Marie began the arduous process of processing tons of pitchblende ore—a mineral that had been mined in Bohemia. They boiled it, filtered it, and chemically separated it, fraction by fraction, always measuring the radioactivity. It was exhausting, painstaking work conducted in their cold, drafty shed. But in 1898, their efforts were rewarded: they isolated two new elements. One they named polonium, after Marie\'s native country. The other, they called radium—the most radioactive element they had found. The scientific community erupted in excitement.' } }] },
    { id: 4, titel: { en: 'Fame and Tragedy' }, blokken: [{ type: 'tekst', inhoud: { en: 'The discovery of radium and polonium made the Curies world-famous. In 1903, Marie became the first woman to earn a doctorate in physics in France. That same year, she and Pierre, along with Henri Becquerel, shared the Nobel Prize in Physics—one of the world\'s highest scientific honors. Remarkably, the Nobel Prize committee initially had not intended to include Marie, planning to honor only Pierre and Becquerel. It was Pierre himself who insisted that his wife\'s contributions be recognized equally. Marie and Pierre had become symbols of scientific progress and intellectual partnership.' }, { type: 'tekst', inhoud: { en: 'The Curies refused to patent their radium discovery, believing that scientific knowledge should be freely available to all researchers and doctors. This decision meant they never became wealthy from their breakthrough, but they adhered to their principles. They had two daughters, Irène and Ève, and Marie tried to balance motherhood with her scientific ambitions—a challenge few women of her era attempted. But tragedy struck on April 19, 1906. Pierre, deep in thought about his research, stepped behind a horse-drawn wagon near the Pont-Neuf in Paris. He was instantly killed. Marie was devastated. Her partner, her scientific collaborator, and the father of her children was gone in an instant.' } }] },
    { id: 5, titel: { en: 'Continuing the Work' }, blokken: [{ type: 'tekst', inhoud: { en: 'Marie faced a choice. She could retreat from science and focus on her daughters, as many people expected a widow to do. Instead, she made a remarkable decision: she would continue the work. The University of Paris offered her Pierre\'s professorship—the first time a French university had appointed a woman to such a position. In her first lecture, before a packed hall of scientists and curious onlookers, Marie spoke about radium and its properties. When she reached the point in her notes where Pierre\'s work ended, she paused, too overcome with emotion to continue. The audience sat in respectful silence. It was a powerful moment, but Marie recovered and finished her lecture. She would not be stopped by grief.' }, { type: 'tekst', inhoud: { en: 'Over the following years, Marie threw herself into her research with even greater intensity. She had already been nominated for a second Nobel Prize for her discovery of radium\'s atomic weight, and in 1911, she won it—becoming the first person ever to win Nobel Prizes in two different scientific fields. This achievement was remarkable, but it also sparked controversy. Some voices in the French press attacked her, partly because she was a woman, and partly because she had become involved in a personal relationship with a fellow scientist, Paul Langevin, who was separated from his wife. The scandal threatened to overshadow her scientific accomplishments, but Marie refused to let public opinion silence her. She continued her work, undeterred.' } }] },
    { id: 6, titel: { en: 'War and Dedication' }, blokken: [{ type: 'tekst', inhoud: { en: 'When World War I erupted in 1914, Europe was plunged into unprecedented conflict. Marie recognized that X-ray machines could save lives on the battlefield by helping doctors locate bullets and identify internal injuries in wounded soldiers. The French military, however, had very few radiography units, and many were far from the front lines. Marie could not sit idle while soldiers suffered. Using her own money and donations, she purchased X-ray equipment and installed it in a van she nicknamed "Petite Curies"—little Curies—after her two daughters. She drove to the front lines herself, operating the equipment and training others to use it.' }, { type: 'tekst', inhoud: { en: 'Marie made multiple trips to dangerous areas near the fighting, often working in conditions that exposed her to both enemy fire and continuous radiation. She wrote about her experiences: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less." Her mobile X-ray units, and the radiography stations she helped establish, saved thousands of lives during the war. After the war, her health had been damaged by the accumulated radiation exposure from years of handling radioactive materials without proper protection—though she did not yet realize how seriously.' }, { type: 'tekst', inhoud: { en: 'Despite her health challenges, Marie continued to work and to train the next generation of scientists. Her daughter Irène followed in her footsteps, becoming a physicist and eventually winning her own Nobel Prize. Marie established the Curie Institute in Paris, a world-leading research center dedicated to the study of radioactivity and its applications in medicine. She traveled internationally, giving lectures and raising funds for her institute. Even as her energy waned, she remained committed to the mission that had defined her life: the pursuit of scientific knowledge and its application to help humanity.' } }] },
    { id: 7, titel: { en: 'The Price of Discovery' }, blokken: [{ type: 'tekst', inhoud: { en: 'In her final years, Marie\'s health deteriorated. The cumulative effects of radiation exposure were taking their toll. She suffered from anemia, joint pain, and other ailments that made it difficult to work. In 1934, at the age of 66, she was admitted to a hospital near Paris. Doctors diagnosed her with aplastic anemia—a rare blood disorder almost certainly caused by decades of exposure to radiation. At this time, very little was known about how to treat radiation sickness, and there was no cure. Marie knew, better than anyone, what was happening to her body. The very element she had devoted her life to studying was destroying her.' }, { type: 'citaat', tekst: { en: 'Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.' }, bron: { en: 'Marie Curie' } }, { type: 'tekst', inhoud: { en: 'On July 4, 1934, Marie Curie died. She was buried in a simple grave in the Panthéon in Paris—a rare honor for a woman. Her life had been dedicated to understanding the mysteries of matter, and in doing so, she had opened doors that would lead to countless medical and technological advances. The periodic table of elements now carries her legacy: Curium, element 96, was named in honor of Marie and Pierre for their contributions to the discovery of radioactivity. She had lived by her principles: to question, to investigate, and to share knowledge with the world.' } }] },
    { id: 8, titel: { en: 'A Revolutionary Legacy' }, blokken: [{ type: 'tekst', inhoud: { en: 'Marie Curie\'s impact on science and society extended far beyond her discoveries of polonium and radium. She shattered the barrier that had prevented women from entering the world of scientific research at the highest levels. Before Marie, it was almost unthinkable for a woman to win a Nobel Prize, to hold a university professorship, or to direct a major scientific institute. She proved that scientific brilliance knows no gender. Today, countless women in physics, chemistry, biology, and medicine cite Marie Curie as their inspiration. She showed the world that a woman could be just as dedicated, just as brilliant, and just as transformative as any man in science.' }, { type: 'tekst', inhoud: { en: 'The applications of her discoveries revolutionized medicine and physics. Radioactivity became central to modern nuclear physics and led to the development of nuclear energy. In medicine, radiotherapy became one of the most powerful tools for treating cancer. X-rays, which she helped popularize, became essential for diagnosis. Medical isotopes derived from her work are used worldwide every day. Her research laid the groundwork for 20th-century physics and changed how we understand the fundamental nature of matter itself. Marie Curie\'s story reminds us that great achievements often require sacrifice, determination, and the courage to pursue your passion despite obstacles. She faced poverty, discrimination because of her gender, personal tragedy, and ultimately, illness caused by her own scientific work. Yet she never wavered in her commitment to understanding nature and using that understanding to benefit humanity. In 2011, on what would have been her 144th birthday, the Google Doodle honored her—introducing millions of people worldwide to her remarkable life. Marie Curie remains one of history\'s most celebrated scientists, a testament to the power of curiosity, perseverance, and the human desire to understand our world.' } }] },
  ]
};

export const twintigsteEeuw: Verhaal[] = [marieCurie];
